local plugins = {
    'ellisonleao/gruvbox.nvim',
    'akinsho/bufferline.nvim',
    "mason-org/mason.nvim",
    "mason-org/mason-lspconfig.nvim",
    'cdelledonne/vim-cmake',
    'christoomey/vim-system-copy',
    'christoomey/vim-titlecase',
    'davidgranstrom/nvim-markdown-preview',
    {'dsznajder/vscode-es7-javascript-react-snippets',run = 'yarn install --frozen-lockfile && yarn compile'},
    { "GCBallesteros/jupytext.nvim", config = true },
    'ggandor/leap.nvim',
    {'hrsh7th/nvim-cmp', requires = {'saadparwaiz1/cmp_luasnip','hrsh7th/cmp-nvim-lsp', 'hrsh7th/cmp-buffer', 'L3MON4D3/LuaSnip'}},
    'JoosepAlviste/nvim-ts-context-commentstring',
    'junegunn/goyo.vim',
    'karb94/neoscroll.nvim',
    {'kyazdani42/nvim-tree.lua',requires = {'kyazdani42/nvim-web-devicons'}},
    {'lewis6991/gitsigns.nvim', requires = {'nvim-lua/plenary.nvim'}},
    'lfilho/cosco.vim',
    'lukas-reineke/indent-blankline.nvim',
    'mattn/emmet-vim',
    { "microsoft/vscode-js-debug", opt = true, run = "npm install --legacy-peer-deps && npm run compile" },
    'mxsdev/nvim-dap-vscode-js',
    'neovim/nvim-lspconfig',
    'norcalli/nvim-colorizer.lua',
    {'nvim-telescope/telescope.nvim',  requires = {'nvim-lua/plenary.nvim'}},
    {'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
    {'nvim-telescope/telescope-dap.nvim' },
    {'nvim-treesitter/nvim-treesitter',run = ':TSUpdate'},
    'nvim-lualine/lualine.nvim',
    'rafamadriz/friendly-snippets',
    { "rcarriga/nvim-dap-ui", requires = {"mfussenegger/nvim-dap", "nvim-neotest/nvim-nio"} },
    'theHamsta/nvim-dap-virtual-text',
    'toppair/reach.nvim',
    'tpope/vim-fugitive',
    'tpope/vim-commentary',
    'tpope/vim-ragtag',
    'tpope/vim-repeat',
    'tpope/vim-surround',
    'tweekmonster/startuptime.vim',
    'untitled-ai/jupyter_ascending.vim',
    'vimwiki/vimwiki',
    'windwp/nvim-autopairs',
    'robitx/gp.nvim'
}

return plugins
